### PR TITLE
Support ECDSA and ED25519 Putty keys.

### PR DESCRIPTION
**Pull request by angelsl**

### CODE REVIEW

**Comment by dlech** [comment]
Thanks for the pull request!

Was [this](http://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/ecdsa.html) released in PuTTY 0.65? I am assuming that this is the reason behind this pull request.

The changes look OK. But I would like to do a bit more for me if you are able.

1. Refactor `aAlgorithm` to just `algorithm` in this function (I'm trying to get away from using prefixes like that).
2. Add some sample .ppk files to `SshAgentLibTests/Resources` that use these keys, both with and without passwords.
3. Add some tests to `SshAgentLibTests/PpkFormatterTest.cs` to test the new .ppk files.

**Comment by angelsl** [comment]
It wasn't in 0.65, but it's in the development versions.

Alright, will do.

**Comment by angelsl** [comment]
I've added tests that verify everything except the ECDSA private key parsing.

It looks correct to me, but I'll add a test in in the next few days (maybe tomorrow) if you don't do so first.

**Comment by angelsl** [comment]
Ok. All has been done.

**Comment by dlech** [comment]
Thanks for finishing this up! I finally had some time to try it out. It all looks good to me. I took the opportunity to refactor out some duplicate code in the PpkFormatter class, so I changed what you had a bit, but the test still passes, so should be good.

You should do another pull request to add your name to the list of authors in those files. :smiley:

**Pull request merged**
