### PR TITLE
Allow to set Certificate member of SshKey and ISshKey

### PR DESCRIPTION
**Pull request by msabatier**
This pull request goes along pull request Opensshcert for dlech/keeagent#310

### CODE REVIEW

**Comment by dlech** [comment]
I tried looking into this a while ago, but it took too much time to try to figure out how to set up a server with certificate support to test this. Would it be possible to create a `Dockerfile` to automate setting up such a server?

**Comment by msabatier** [comment]
Hello David,
Sure I will try to setup something, hopefully this week-end or at least before end of next week.

**Comment by msabatier** [comment]
Done.

I was not exactly sure where to put the files so I chose to create a new directory `SshAgentLibTests/Resources/cert_test`.
I added a README in the same directory on how to run the image.
I also pushed a commit to KeeAgent to update the test database to make it work with the test-CA key I had to create for the Docker image.

Let me know if you have any issue.

**Comment by dlech** [comment]
What is the passphrase for the `test-CA` file?

**Comment by msabatier** [comment]
Sorry forgot to add that to the readme it is
      testtest

**Comment by dlech** [comment]
I tried that yesterday and it doesn't seem to work (it is the passphrase for the SSH key that was signed with the certificate, but not for the certificate itself).

**Comment by msabatier** [comment]
Just tried again and it is working for me

```
ssh-keygen -t rsa-sha2-256 -s test-CA -I test -n testtest -V +3600d -z 1 test_keeagent.pub
Enter passphrase:
Signed user key test_keeagent-cert.pub: id "test" serial 1 for testtest valid from 2022-05-23T18:12:00 to 2032-03-31T18:13:30
```

**Comment by dlech** [comment]
Thanks for the Dockerfile. It was very helpful in making sure this was actually working correctly. I have picked up a modified version of that commit from this PR. Adding proper support turned out to be a bit more complicated given other changes I have made recently (to fix other unrelated issues). And there was some untangling to do to make this work in client mode as well. But it should be mostly working now.

**Pull request closed without merging**
